const db = require('../config/db');
const path = require('path');
const fs = require('fs');
const { sendReportEmail } = require('../utils/mailer');

const getAppointmentByToken = async (req, res) => {
  const { token } = req.params;
  try {
    const [appts] = await db.query(
      `SELECT a.*, u.name as patient_name, u.email as patient_email, u.phone as patient_phone,
        tp.name as package_name, tp.pre_requirements,
        p.age, p.gender, p.blood_group
       FROM appointments a
       LEFT JOIN users u ON a.patient_id = u.id
       LEFT JOIN test_packages tp ON a.test_package_id = tp.id
       LEFT JOIN patients p ON a.patient_id = p.user_id
       WHERE a.token_number = ? AND a.status IN ('completed','in_progress','checked_in')`,
      [token]
    );
    if (appts.length === 0)
      return res.status(404).json({ message: 'No eligible appointment found. Patient must be checked in or tests completed.' });
    const [existing] = await db.query('SELECT id FROM reports WHERE appointment_id = ?', [appts[0].id]);
    if (existing.length > 0)
      return res.status(400).json({ message: 'Report already created for this appointment.' });
    res.json(appts[0]);
  } catch (err) { res.status(500).json({ message: 'Server error', error: err.message }); }
};

const createReport = async (req, res) => {
  const { token_number, report_title, report_content, dispatch_date } = req.body;
  const doctor_id = req.user.id;
  try {
    const [appts] = await db.query('SELECT * FROM appointments WHERE token_number = ?', [token_number]);
    if (appts.length === 0)
      return res.status(404).json({ message: 'Appointment not found for this token' });
    const appt = appts[0];

    // Handle PDF attachment if uploaded
    let pdfPath = null;
    if (req.file) {
      pdfPath = req.file.filename;
    }

    const [result] = await db.query(
      `INSERT INTO reports (appointment_id, patient_id, doctor_id, report_title, report_content, dispatch_date, is_available, pdf_path) 
       VALUES (?, ?, ?, ?, ?, ?, true, ?)`,
      [appt.id, appt.patient_id, doctor_id, report_title, report_content, dispatch_date || null, pdfPath]
    );

    await db.query('INSERT INTO notifications (user_id, title, message, type) VALUES (?, ?, ?, ?)',
      [appt.patient_id, 'Report Available', 'Your diagnostic report is now ready. Check your reports section or email.', 'report']);
    await db.query('UPDATE appointments SET status = "completed" WHERE id = ?', [appt.id]);

    // Send report email with PDF
    try {
      const [users] = await db.query('SELECT * FROM users WHERE id = ?', [appt.patient_id]);
      const [docs] = await db.query('SELECT name FROM users WHERE id = ?', [doctor_id]);

      let pdfBuffer = null;
      let pdfFilename = `MediCare_Report_${token_number}.pdf`;

      if (pdfPath) {
        // Doctor uploaded a PDF — attach it
        const pdfFile = path.join(__dirname, '../uploads', pdfPath);
        if (fs.existsSync(pdfFile)) pdfBuffer = fs.readFileSync(pdfFile);
        pdfFilename = `MediCare_Report_${token_number}.pdf`;
      } else {
        // Generate simple text-based PDF content as buffer
        const content = [
          `MEDICARE GOVERNMENT HOSPITAL`,
          `═══════════════════════════════════════`,
          `DIAGNOSTIC REPORT`,
          `═══════════════════════════════════════`,
          ``,
          `Report Title  : ${report_title}`,
          `Token Number  : ${token_number}`,
          `Patient Name  : ${users[0]?.name}`,
          `Patient Email : ${users[0]?.email}`,
          `Date          : ${new Date(appt.appointment_date).toDateString()}`,
          `Doctor        : Dr. ${docs[0]?.name}`,
          `Prepared On   : ${new Date().toDateString()}`,
          ``,
          `═══════════════════════════════════════`,
          `FINDINGS & RESULTS`,
          `═══════════════════════════════════════`,
          ``,
          report_content,
          ``,
          `═══════════════════════════════════════`,
          `This report is generated by MediCare Hospital.`,
          `For queries contact: geetured1@gmail.com`,
        ].join('\n');
        pdfBuffer = Buffer.from(content, 'utf-8');
        pdfFilename = `MediCare_Report_${token_number}.txt`;
      }

      await sendReportEmail(
        users[0],
        { report_title, token_number },
        appt,
        pdfBuffer,
        pdfFilename
      );
    } catch (mailErr) {
      console.error('Report email failed:', mailErr.message);
    }

    res.status(201).json({ message: 'Report created, patient notified by email', report_id: result.insertId });
  } catch (err) { res.status(500).json({ message: 'Server error', error: err.message }); }
};

const getMyReports = async (req, res) => {
  try {
    const [reports] = await db.query(
      `SELECT r.*, u.name as doctor_name, a.appointment_date, a.token_number, tp.name as package_name
       FROM reports r
       LEFT JOIN users u ON r.doctor_id = u.id
       LEFT JOIN appointments a ON r.appointment_id = a.id
       LEFT JOIN test_packages tp ON a.test_package_id = tp.id
       WHERE r.patient_id = ? AND r.is_available = true
       ORDER BY r.created_at DESC`,
      [req.user.id]
    );
    res.json(reports);
  } catch (err) { res.status(500).json({ message: 'Server error', error: err.message }); }
};

const getAllReports = async (req, res) => {
  try {
    const [reports] = await db.query(
      `SELECT r.*, u.name as patient_name, u.phone as patient_phone, a.appointment_date, a.token_number
       FROM reports r
       LEFT JOIN users u ON r.patient_id = u.id
       LEFT JOIN appointments a ON r.appointment_id = a.id
       WHERE r.doctor_id = ?
       ORDER BY r.created_at DESC`,
      [req.user.id]
    );
    res.json(reports);
  } catch (err) { res.status(500).json({ message: 'Server error', error: err.message }); }
};

module.exports = { getAppointmentByToken, createReport, getMyReports, getAllReports };
